version: "3.7"

networks:
  spex:

volumes:
  ms_splitter:

services:
  arangodb:
    image: arangodb:3.7.7
    container_name: spex-arangodb
    restart: always
    networks:
      spex:
        aliases:
          - spex-arangodb
    ports:
      - 8529
    env_file:
      - ./.env.local
    volumes:
      - ~/spex_db:/var/lib/arangodb3

  memcached:
    image: memcached:latest
    container_name: spex-memcached
    restart: always
    networks:
      spex:
        aliases:
          - spex-memcached
    ports:
      - 11211
    entrypoint:
      - memcached
      - -m 64

  redisjson:
    container_name: spex_redisjson
    restart: always
    networks:
      spex:
        aliases:
          - spex_redisjson
    ports:
      - 6379
    build:
      context: ./microservices/redis
      dockerfile: Dockerfile

  ms_session_refresher:
    container_name: spex-ms-session-refresher
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-session-refresher
    env_file:
      - ./microservices/ms-session-refresher/.env
      - ./microservices/.env.common
      - ./microservices/.env.common.local
    build:
      context: .
      dockerfile: ./microservices/ms-session-refresher/Dockerfile
    depends_on:
      - memcached

  ms_splitter:
    container_name: spex-ms-splitter
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-splitter
    volumes:
      - ${HOST_DATA_STORAGE}:/DATA_STORAGE
    env_file:
      - ./microservices/ms-splitter/.env
      - ./microservices/.env.common
      - ./microservices/.env.common.local
    build:
      context: .
      dockerfile: ./microservices/ms-splitter/Dockerfile
    depends_on:
      - redisjson
      - arangodb

  ms_task_runner:
    container_name: spex-ms-task-runner
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-task-runner
    volumes:
      - ms_splitter:/DATA_STORAGE
    env_file:
      - ./microservices/ms-task-runner/.env
      - ./microservices/.env.common
      - ./microservices/.env.common.local
    build:
      context: .
      dockerfile: ./microservices/ms-task-runner/Dockerfile
    depends_on:
      - ms_splitter

  ms_collector:
    container_name: spex-ms-collector
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-collector
    volumes:
      - ms_splitter:/DATA_STORAGE
    env_file:
      - ./microservices/ms-collector/.env
      - ./microservices/.env.common
      - ./microservices/.env.common.local
    build:
      context: .
      dockerfile: ./microservices/ms-collector/Dockerfile
    depends_on:
      - ms_splitter

#  ms_pipeline_manager:
#    container_name: spex-ms-pipeline-manager
#    networks:
#      backend_genentech:
#        aliases:
#          - spex-ms-collector
#    env_file:
#      - ./micro-services/ms-pipeline-manager/.env
#      - ./micro-services/.env.common
#      - ./micro-services/.env.common.local
#    build:
#      context: .
#      dockerfile: ./micro-services/ms-pipeline-manager/Dockerfile

  backend:
    container_name: spex-backend
    restart: always
    networks:
      spex:
        aliases:
          - spex-backend
    volumes:
      - ${HOST_DATA_STORAGE}:/DATA_STORAGE
    ports:
      - 8080
    env_file:
      - ./.env.local
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - arangodb
      - memcached

  nginx:
    image: nginx:1.19.8
    container_name: spex-nginx
    restart: always
    networks:
      - spex
    volumes:
      - ../frontend/build:/usr/share/spex/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
