version: "3.7"

networks:
  genentech:

services:
  arangodb:
    image: arangodb:3.7.7
    container_name: roche-arangodb
    restart: always
    networks:
      genentech:
        aliases:
          - roche-arangodb
    ports:
      - 8529
    env_file:
      - ./.env.local
    volumes:
      - /home/arangodb_data:/var/lib/arangodb3
  memcached:
    image: memcached:latest
    container_name: roche-memcached
    restart: always
    networks:
      genentech:
        aliases:
          - roche-memcached
    ports:
      - 11211
    entrypoint:
      - memcached
      - -m 64
  nginx:
    image: nginx:1.19.8
    container_name: roche-nginx
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - genentech
  backend:
    container_name: roche-backend
    networks:
      genentech:
        aliases:
          - roche-backend
    ports:
      - 8080
    env_file:
      - ./.env.local
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - arangodb
      - memcached
