version: "3.7"

networks:
  backend_genentech:

services:
  redisjson:
    container_name: spex_redisjson
    networks:
      backend_genentech:
        aliases:
          - spex_redisjson
    ports:
      - '6379:6379'
    build:
      context: ./redis
      dockerfile: Dockerfile

  memcached:
    image: 'bitnami/memcached:latest'
    container_name: spex_memcached
    ports:
      - '11211:11211'
    networks:
      backend_genentech:
        aliases:
          - spex-memcached

  ms_ome_session_refresher:
    container_name: spex-ms-ome-session-refresher
    networks:
      backend_genentech:
        aliases:
          - spex-ms-ome-session-refresher
    env_file:
      - ./ms-session-refresher/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./micro-services/ms-session-refresher/Dockerfile
    depends_on:
      - memcached

  ms_splitter:
    container_name: spex-ms-splitter
    networks:
      backend_genentech:
        aliases:
          - spex-ms-splitter
    volumes:
      - C:\\temp\\DATA_STORAGE:/DATA_STORAGE
    env_file:
      - ./ms-splitter/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./micro-services/ms-splitter/Dockerfile
    depends_on:
      - redisjson

  ms_task_runner:
    container_name: spex-ms-task-runner
    networks:
      backend_genentech:
        aliases:
          - spex-ms-task-runner
    volumes:
      - ms_splitter:/DATA_STORAGE
    env_file:
      - ./ms-task-runner/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./micro-services/ms-task-runner/Dockerfile
    depends_on:
      - redisjson
      - ms_splitter

  ms_collector:
    container_name: spex-ms-collector
    networks:
      backend_genentech:
        aliases:
          - spex-ms-collector
    volumes:
      - ms_splitter:/DATA_STORAGE
    env_file:
      - ./ms-collector/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./micro-services/ms-collector/Dockerfile
    depends_on:
      - redisjson
      - ms_splitter

  ms_pipeline_manager:
    container_name: spex-ms-pipeline-manager
    networks:
      backend_genentech:
        aliases:
          - spex-ms-collector
    env_file:
      - ./ms-pipeline-manager/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./micro-services/ms-pipeline-manager/Dockerfile

volumes:
  ms_splitter:
