version: "3.7"

networks:
  backend_genentech:

services:
  redisjson:
    container_name: spex_redisjson
    networks:
      backend_genentech:
        aliases:
          - spex_redisjson
    ports:
      - '6379:6379'
    build:
      context: ./redis
      dockerfile: Dockerfile

  memcached:
    image: 'bitnami/memcached:latest'
    container_name: spex_memcached
    ports:
      - '11211:11211'
    networks:
      backend_genentech:
        aliases:
          - spex-memcached

  ms_ome_session_refresher:
    container_name: roche-ms-ome-session-refresher
    networks:
      backend_genentech:
        aliases:
          - roche-ms-ome-session-refresher
    env_file:
      - ./ms-session-refresher/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: .
      dockerfile: ./ms-session-refresher/Dockerfile
    depends_on:
      - memcached

  ms_splitter:
    container_name: roche-ms-splitter
    networks:
      backend_genentech:
        aliases:
          - roche-ms-splitter
    volumes:
      - C:\\temp\\DATA_STORAGE:/DATA_STORAGE
    env_file:
      - ./ms-splitter/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: .
      dockerfile: ./ms-splitter/Dockerfile
    depends_on:
      - redisjson

  ms_task_runner:
    container_name: roche-ms-task-runner
    networks:
      backend_genentech:
        aliases:
          - roche-ms-task-runner
    volumes_from:
      - ms_splitter
    env_file:
      - ./ms-task-runner/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: .
      dockerfile: ./ms-task-runner/Dockerfile
    depends_on:
      - redisjson
      - ms_splitter

  ms_collector:
    container_name: roche-ms-collector
    networks:
      backend_genentech:
        aliases:
          - roche-ms-collector
    volumes_from:
      - ms_splitter
    env_file:
      - ./ms-collector/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: .
      dockerfile: ./ms-collector/Dockerfile
    depends_on:
      - redisjson
      - ms_splitter
