# don't forget to add system environment variable HOST_DATA_STORAGE

version: "3.7"

networks:
  spex:

services:
  redisjson:
    container_name: spex-redisjson
    restart: always
    networks:
      spex:
        aliases:
          - spex-redisjson
    ports:
      - '6379:6379'
    build:
      context: ./redis
      dockerfile: Dockerfile

  memcached:
    image: memcached:latest
    container_name: spex-memcached
    restart: always
    networks:
      spex:
        aliases:
          - spex-memcached
    ports:
      - '11211:11211'
    entrypoint:
      - memcached
      - -m 64

  ms_omero_sessions:
    container_name: spex-ms-omero-sessions
    restart: always
    ports:
      - '8448:8448'
    networks:
      spex:
        aliases:
          - spex-ms-omero-sessions
    env_file:
      - ./ms-omero-sessions/.env
      - ./ms-omero-sessions/.env.local
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./../..
      dockerfile: ./microservices/ms-omero-sessions/Dockerfile
    depends_on:
      - memcached

  ms_image_loader:
    container_name: spex-ms-image-loader
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-image-loader
    volumes:
      - data_storage:/DATA_STORAGE
    env_file:
      - ./ms-omero-image-downloader/.env
      - ./ms-omero-image-downloader/.env.local
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./../..
      dockerfile: ./microservices/ms-omero-image-downloader/Dockerfile
    depends_on:
      - ms_omero_sessions
      - redisjson

  ms_collector:
    container_name: spex-ms-collector
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-collector
    volumes:
      - data_storage:/DATA_STORAGE
    env_file:
      - ./ms-collector/.env
      - ./ms-collector/.env.local
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./../..
      dockerfile: ./microservices/ms-collector/Dockerfile

  ms_pipeline_manager:
    container_name: spex-ms-pipeline-manager
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-collector
    env_file:
      - ./ms-pipeline-manager/.env
      - ./ms-pipeline-manager/.env.local
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./../..
      dockerfile: ./microservices/ms-pipeline-manager/Dockerfile

  ms_job_manager:
    container_name: spex-ms-job-manager
    restart: always
    networks:
      spex:
        aliases:
          - spex-job-manager
    volumes:
      - data_storage:/DATA_STORAGE
    env_file:
      - ./ms-job-manager/.env
      - ./ms-job-manager/.env.local
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./../..
      dockerfile: ./microservices/ms-job-manager/Dockerfile

volumes:
  data_storage:
    driver: local
    driver_opts:
      device: ${HOST_DATA_STORAGE}
      o: bind
      type: none
