version: "3.7"

networks:
  spex:

services:
  redisjson:
    container_name: spex_redisjson
    restart: always
    networks:
      spex:
        aliases:
          - spex_redisjson
    ports:
      - '6379:6379'
    build:
      context: ./redis
      dockerfile: Dockerfile

  memcached:
    image: memcached:latest
    container_name: spex-memcached
    restart: always
    networks:
      spex:
        aliases:
          - spex-memcached
    ports:
      - '11211:11211'
    entrypoint:
      - memcached
      - -m 64

  ms_session_refresher:
    container_name: spex-ms-session-refresher
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-session-refresher
    env_file:
      - ./ms-session-refresher/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./microservices/ms-session-refresher/Dockerfile
    depends_on:
      - memcached

  ms_splitter:
    container_name: spex-ms-splitter
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-splitter
    volumes:
      - ${HOST_DATA_STORAGE}:/DATA_STORAGE
    env_file:
      - ./ms-splitter/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./microservices/ms-splitter/Dockerfile
    depends_on:
      - redisjson

  ms_task_runner:
    container_name: spex-ms-task-runner
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-task-runner
    volumes:
      - ms_splitter:/DATA_STORAGE
    env_file:
      - ./ms-task-runner/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./microservices/ms-task-runner/Dockerfile
    depends_on:
      - ms_splitter

  ms_collector:
    container_name: spex-ms-collector
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-collector
    volumes:
      - ms_splitter:/DATA_STORAGE
    env_file:
      - ./ms-collector/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./microservices/ms-collector/Dockerfile
    depends_on:
      - ms_splitter

  ms_pipeline_manager:
    container_name: spex-ms-pipeline-manager
    restart: always
    networks:
      spex:
        aliases:
          - spex-ms-collector
    env_file:
      - ./ms-pipeline-manager/.env
      - ./.env.common
      - ./.env.common.local
    build:
      context: ./..
      dockerfile: ./microservices/ms-pipeline-manager/Dockerfile

volumes:
  ms_splitter:
